{% set version = "0.12.1" %}
{% set min_python = "python >=3.7" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}


package:
  name: typer-split
  version: {{ version }}

source:
  - folder: typer-slim
    url: https://pypi.io/packages/source/t/typer-slim/typer_slim-{{ version }}.tar.gz
    sha256: a1d74b0ffad59a42fc06bc9e9661402267f0e1c072f5ac8b751392e6a24ff37c
  - folder: typer-cli
    url: https://pypi.io/packages/source/t/typer-cli/typer_cli-{{ version }}.tar.gz
    sha256: 2576e55d3418b07843cfefae1f3c65a9e47156d34abeccc6c2039691bd5286c6
    patches:
      - 0000-typer-cli-no-entry-point.patch
  - folder: typer
    url: https://pypi.io/packages/source/t/typer/typer-{{ version }}.tar.gz
    sha256: 72d218ef3c686aed9c6ff3ca25b238aee0474a1628b29c559b18b634cfdeca88

build:
  number: 0
  noarch: python

outputs:
  # packages with source are `noarch: python`, and should use `{{ min_python }}` in `host` and `run``
  - name: typer-slim
    build:
      noarch: python
      script: {{ PYTHON }} {{ RECIPE_DIR }}/build_typer.py
    requirements:
      host:
        - {{ min_python }}
        - pdm-backend
        - pip
        - python-build
      run:
        - {{ min_python }}
        - click >=8.0.0
        - typing_extensions >=3.7.4.3
      run_constrained:
        # avoid clobbering historic `typer` versions
        - {{ pin_subpackage("typer", exact=True) }}
        # see typer-slim-standard `run` for concrete pinss
        - rich >=10.11.0,<14.0.0
        - shellingham >=1.3.0,<2.0.0
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: typer-cli
    build:
      noarch: python
      script: {{ PYTHON }} {{ RECIPE_DIR }}/build_typer.py
    requirements:
      host:
        - {{ min_python }}
        - pdm-backend
        - pip
        - python-build
      run:
        - {{ min_python }}
        - {{ pin_subpackage("typer", exact=True) }}
    test:
      requires:
        - pip
      commands:
        - pip check
        - typer --version
        - typer --help

  - name: typer
    build:
      noarch: python
      script: {{ PYTHON }} {{ RECIPE_DIR }}/build_typer.py
      entry_points:
        # won't actually run, but needs to be here to get proper wrapper generated
        - typer = typer.cli:main
    requirements:
      host:
        - {{ min_python }}
        - pdm-backend
        - pip
        - python-build
      run:
        - {{ min_python }}
        - {{ pin_subpackage("typer-slim-standard", exact=True) }}
    test:
      source_files:
        - typer/tests
        - typer/docs_src
      requires:
        - pip
        - pytest
        - coverage
      commands:
        - pip check
        - typer --version
        - typer --help
        - cd typer && coverage run --source=typer --branch -m pytest -vv --color=yes --tb=long -k "not ((multiple_values and main) or completion)"
        - coverage report --show-missing --skip-covered --fail-under=66

  # dep-only packages are `noarch: generic`, with no `host`
  - name: typer-slim-standard
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("typer-slim", exact=True) }}
        # see `typer-slim` for pins in `run_constrained`
        - rich
        - shellingham
    test:
      source_files:
        - typer-slim/tests
        - typer-slim/docs_src
      imports:
        - typer
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/tiangolo/typer
  license: MIT
  license_family: MIT
  license_file: typer-slim/LICENSE
  summary: Typer, build great CLIs. Easy to code. Based on Python type hints.
  doc_url: https://typer.tiangolo.com

extra:
  feedstock-name: typer
  recipe-maintainers:
    - dfornika
    - bollwyvl
