# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.21.2"
  python_check_max: "3.14"

recipe:
  name: typer-split
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/typer-slim/typer_slim-${{ version }}.tar.gz
    sha256: 78f20d793036a62aaf9c3798306142b08261d4b2a941c6e463081239f062a2f9
    target_directory: typer-slim
  - url: https://pypi.org/packages/source/t/typer-cli/typer_cli-${{ version }}.tar.gz
    sha256: f54265ed564cbfa0cfa5ed2ed6b4ea3cf7ef9209e520a8703d523623358cae59
    target_directory: typer-cli
    patches:
      - 0000-typer-cli-no-entry-point.patch
  - url: https://pypi.org/packages/source/t/typer/typer-${{ version }}.tar.gz
    sha256: 1abd95a3b675e17ff61b0838ac637fe9478d446d62ad17fa4bb81ea57cc54028
    target_directory: typer

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: typer-slim
    build:
      noarch: python
      script:
        interpreter: python
        file: build_typer.py
    requirements:
      host:
        - pdm-backend
        - pip
        - python ${{ python_min }}.*
        - python-build
      run:
        - annotated-doc >=0.0.2
        - python >=${{ python_min }}
        - click >=8.0.0
        - typing_extensions >=3.7.4.3
      run_constraints:
        - typer ${{ version }}.*
        - rich >=10.11.0
        - shellingham >=1.3.0
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: typer-cli
    build:
      noarch: python
      script:
        interpreter: python
        file: build_typer.py
    requirements:
      host:
        - pdm-backend
        - pip
        - python ${{ python_min }}.*
        - python-build
      run:
        - ${{ pin_subpackage("typer", exact=True) }}
        - python >=${{ python_min }}
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - typer --version
          - typer --help

  - package:
      name: typer
    build:
      noarch: python
      script:
        interpreter: python
        file: build_typer.py
      python:
        entry_points:
          - typer = typer.cli:main
    requirements:
      host:
        - pdm-backend
        - pip
        - python ${{ python_min }}.*
        - python-build
      run:
        - ${{ pin_subpackage("typer-slim-standard", exact=True) }}
        - python >=${{ python_min }}
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version: ${{ python_min }}.*
      - files:
          source:
            - typer/tests/
            - typer/docs_src/
        requirements:
          run:
            - coverage
            - pytest
            - python ${{ python_min }}.*
        script:
          - typer --version
          - typer --help
          - cd typer
          - coverage run --source=typer --branch -m pytest -vv --color=yes --tb=long -k "not ((multiple_values and main) or completion or invalid_score)"
          - coverage report --show-missing --skip-covered --fail-under=66

  - package:
      name: typer-slim-standard
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("typer-slim", exact=True) }}
        # see `typer-slim` for pins in `run_constrained`
        - rich
        - shellingham
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: typer-slim/LICENSE
  summary: Typer, build great CLIs. Easy to code. Based on Python type hints.
  homepage: https://pypi.org/project/typer
  documentation: https://typer.tiangolo.com
  repository: https://github.com/tiangolo/typer

extra:
  feedstock-name: typer
  recipe-maintainers:
    - thewchan
    - dfornika
    - bollwyvl
    - fcollonval
