# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.23.0"
  python_check_max: "3.14"

recipe:
  name: typer-split
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/typer-slim/typer_slim-${{ version }}.tar.gz
    sha256: be8b60243df27cfee444c6db1b10a85f4f3e54d940574f31a996f78aa35a8254
    target_directory: typer-slim
  - url: https://pypi.org/packages/source/t/typer-cli/typer_cli-${{ version }}.tar.gz
    sha256: 0e690e52b89c3ced1965485b7cfe235fe9543afe9e7b8e39b8901f4fed3a94a9
    target_directory: typer-cli
    patches:
      - 0000-typer-cli-no-entry-point.patch
  - url: https://pypi.org/packages/source/t/typer/typer-${{ version }}.tar.gz
    sha256: d8378833e47ada5d3d093fa20c4c63427cc4e27127f6b349a6c359463087d8cc
    target_directory: typer

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: typer-slim
    build:
      noarch: python
      script:
        interpreter: python
        file: build_typer.py
    requirements:
      host:
        - pdm-backend
        - pip
        - python ${{ python_min }}.*
        - python-build
      run:
        - annotated-doc >=0.0.2
        - python >=${{ python_min }}
        - click >=8.0.0
      run_constraints:
        - typer ${{ version }}.*
        - rich >=10.11.0
        - shellingham >=1.3.0
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      homepage: https://pypi.org/project/typer-slim

  - package:
      name: typer-cli
    build:
      noarch: python
      script:
        interpreter: python
        file: build_typer.py
    requirements:
      host:
        - pdm-backend
        - pip
        - python ${{ python_min }}.*
        - python-build
      run:
        - ${{ pin_subpackage("typer", exact=True) }}
        - python >=${{ python_min }}
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - typer --version
          - typer --help
    about:
      homepage: https://pypi.org/project/typer-cli

  - package:
      name: typer
    build:
      noarch: python
      script:
        interpreter: python
        file: build_typer.py
      python:
        entry_points:
          - typer = typer.cli:main
    requirements:
      host:
        - pdm-backend
        - pip
        - python ${{ python_min }}.*
        - python-build
      run:
        - ${{ pin_subpackage("typer-slim-standard", exact=True) }}
        - python >=${{ python_min }}
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version: ${{ python_min }}.*
      - files:
          source:
            - typer/tests/
            - typer/docs_src/
        requirements:
          run:
            - coverage
            - pytest
            - python ${{ python_min }}.*
        script:
          - typer --version
          - typer --help
          - cd typer
          - coverage run --source=typer --branch -m pytest -vv --color=yes --tb=long -k "not ((multiple_values and main) or completion or invalid_score)"
          - coverage report --show-missing --skip-covered --fail-under=66

  - package:
      name: typer-slim-standard
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("typer-slim", exact=True) }}
        # see `typer-slim` for pins in `run_constrained`
        - rich
        - shellingham
    tests:
      - python:
          imports: typer
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://pypi.org/project/typer-slim

about:
  license: MIT
  license_file: typer-slim/LICENSE
  summary: Typer, build great CLIs. Easy to code. Based on Python type hints.
  homepage: https://pypi.org/project/typer
  documentation: https://typer.tiangolo.com
  repository: https://github.com/tiangolo/typer

extra:
  feedstock-name: typer
  recipe-maintainers:
    - thewchan
    - dfornika
    - bollwyvl
    - fcollonval
